/**
 * The workforce.
 *
 * Humans are drawn on HUMAN_SKELETON and therefore read as tall next to the
 * dwarfs; machines get a `scale` and `girth` that make them unmistakably
 * objects rather than people. The IoT appliances are deliberately oversized —
 * a fridge you cannot read at a glance is not a joke, it is furniture.
 *
 * `outfit` is pinned at 1 for everything here: nobody on the payroll gets a
 * transformation scene. Suits keep the black glasses and the earpiece, which
 * is what `shades: true` plus the dark palette buys us for free.
 *
 * Move id convention: `e_<verb>`.
 */

import type { EnemyDef, EnemyKind } from '@/core/types';

export const ENEMIES: Record<EnemyKind, EnemyDef> = {
  // ── Humans in suits ────────────────────────────────────────────────────────
  suit_guard: {
    id: 'suit_guard',
    name: 'Corporate Security',
    health: 58,
    speed: 1.0,
    power: 1.0,
    aggression: 0.62,
    spacing: 24,
    style: {
      scale: 1.26,
      girth: 0.94,
      headSize: 0.9,
      beardLength: 0,
      beardStyle: 'none',
      skin: '#d8a682',
      skinShade: '#a9784f',
      hair: '#241d1a',
      hatColor: '#14141a',
      tunicColor: '#1a1a22',
      jacketColor: '#101018',
      jacketAccent: '#3d4250',
      spikes: 0,
      shades: true,
      outfit: 1,
      tattoo: 'none',
      cigar: false,
    },
    moves: { light: 'e_jab', heavy: 'e_haymaker' },
    weapon: 'chain',
    points: 100,
    ai: {
      reactionFrames: 18,
      blockSkill: 0.14,
      comboSkill: 0.25,
      swarm: 0.5,
      behaviour: 'rusher',
    },
  },

  taser_guard: {
    id: 'taser_guard',
    name: 'Compliance Officer',
    health: 68,
    speed: 0.96,
    power: 0.9,
    aggression: 0.5,
    spacing: 40,
    style: {
      scale: 1.26,
      girth: 1.0,
      headSize: 0.9,
      beardLength: 0.35,
      beardStyle: 'stubble',
      skin: '#c9926e',
      skinShade: '#9a6845',
      hair: '#1b1714',
      hatColor: '#1b2230',
      tunicColor: '#232c3c',
      jacketColor: '#182030',
      jacketAccent: '#6ee4ff',
      spikes: 0,
      shades: true,
      outfit: 1,
      tattoo: 'none',
      cigar: false,
    },
    moves: { light: 'e_taser_jab', heavy: 'e_taser_zap' },
    weapon: 'taser',
    points: 150,
    ai: {
      reactionFrames: 14,
      blockSkill: 0.22,
      comboSkill: 0.2,
      swarm: 0.35,
      behaviour: 'spacer',
    },
  },

  gunman: {
    id: 'gunman',
    name: 'Close Protection',
    health: 52,
    speed: 1.02,
    power: 1.5,
    aggression: 0.22,
    spacing: 150,
    style: {
      scale: 1.28,
      girth: 0.88,
      headSize: 0.88,
      beardLength: 0,
      beardStyle: 'none',
      skin: '#e0b48e',
      skinShade: '#b1825a',
      hair: '#3a2c22',
      hatColor: '#121218',
      tunicColor: '#1d1d26',
      jacketColor: '#0e0e14',
      jacketAccent: '#ffcf5c',
      spikes: 0,
      shades: true,
      outfit: 1,
      tattoo: 'none',
      cigar: false,
    },
    moves: { light: 'e_pistol_whip', heavy: 'e_haymaker', ranged: 'e_shoot' },
    weapon: 'pistol',
    points: 220,
    ai: {
      reactionFrames: 22,
      blockSkill: 0.08,
      comboSkill: 0.05,
      swarm: 0.15,
      behaviour: 'sniper',
    },
  },

  riot_guard: {
    id: 'riot_guard',
    name: 'Public Order Unit',
    health: 124,
    speed: 0.78,
    power: 1.15,
    aggression: 0.4,
    spacing: 20,
    style: {
      scale: 1.34,
      girth: 1.22,
      headSize: 0.94,
      beardLength: 0,
      beardStyle: 'none',
      skin: '#c08a63',
      skinShade: '#8f6140',
      hair: '#15120f',
      hatColor: '#2b3340',
      tunicColor: '#333c4c',
      jacketColor: '#212836',
      jacketAccent: '#f2c53d',
      spikes: 0,
      shades: true,
      outfit: 1,
      tattoo: 'none',
      cigar: false,
    },
    moves: { light: 'e_shield_bash', heavy: 'e_shield_charge' },
    weapon: 'riotshield',
    points: 280,
    ai: {
      reactionFrames: 12,
      blockSkill: 0.72,
      comboSkill: 0.3,
      swarm: 0.25,
      behaviour: 'turtle',
    },
  },

  // ── Machines ───────────────────────────────────────────────────────────────
  security_bot: {
    id: 'security_bot',
    name: 'Patrol Unit',
    health: 155,
    speed: 0.82,
    power: 1.45,
    aggression: 0.78,
    spacing: 26,
    style: {
      scale: 1.42,
      girth: 1.3,
      headSize: 0.7,
      beardLength: 0,
      beardStyle: 'none',
      skin: '#c9d2dc',
      skinShade: '#8d97a4',
      hair: '#2a3140',
      hatColor: '#39424f',
      tunicColor: '#5a6675',
      jacketColor: '#414c5b',
      jacketAccent: '#ff4d4d',
      spikes: 2,
      shades: false,
      outfit: 1,
      tattoo: 'barcode',
      cigar: false,
    },
    moves: { light: 'e_baton', heavy: 'e_bot_slam' },
    weapon: 'ironbar',
    points: 340,
    ai: {
      reactionFrames: 20,
      blockSkill: 0.3,
      comboSkill: 0.45,
      swarm: 0.7,
      behaviour: 'rusher',
    },
  },

  vacuum_bot: {
    id: 'vacuum_bot',
    name: 'Autonomous Floor Care',
    health: 38,
    speed: 1.5,
    power: 0.55,
    aggression: 0.9,
    spacing: 10,
    style: {
      scale: 0.62,
      girth: 1.9,
      headSize: 0.42,
      beardLength: 0,
      beardStyle: 'none',
      skin: '#3c4250',
      skinShade: '#252a35',
      hair: '#1b1f28',
      hatColor: '#4c5361',
      tunicColor: '#2f3540',
      jacketColor: '#252b36',
      jacketAccent: '#5ce1e6',
      spikes: 0,
      shades: false,
      outfit: 1,
      tattoo: 'none',
      cigar: false,
    },
    moves: { light: 'e_vac_ram', heavy: 'e_vac_spin' },
    weapon: 'pipe',
    points: 90,
    ai: {
      reactionFrames: 8,
      blockSkill: 0,
      comboSkill: 0.1,
      swarm: 1.0,
      behaviour: 'erratic',
    },
  },

  iot_fridge: {
    id: 'iot_fridge',
    name: 'Smart Refrigerator',
    health: 210,
    speed: 0.5,
    power: 1.6,
    aggression: 0.35,
    spacing: 22,
    style: {
      scale: 1.62,
      girth: 1.72,
      headSize: 0.55,
      beardLength: 0,
      beardStyle: 'none',
      skin: '#dfe6ee',
      skinShade: '#a8b3c0',
      hair: '#8e9aa8',
      hatColor: '#cfd8e2',
      tunicColor: '#e6edf4',
      jacketColor: '#c3ccd6',
      jacketAccent: '#4fc3f7',
      spikes: 0,
      shades: false,
      outfit: 1,
      tattoo: 'barcode',
      cigar: false,
    },
    moves: { light: 'e_door_swing', heavy: 'e_fridge_crush', ranged: 'e_ice_spit' },
    weapon: 'cybertruck_door',
    points: 420,
    ai: {
      reactionFrames: 26,
      blockSkill: 0.5,
      comboSkill: 0.15,
      swarm: 0.2,
      behaviour: 'turtle',
    },
  },

  iot_speaker: {
    id: 'iot_speaker',
    name: 'Always-Listening Speaker',
    health: 88,
    speed: 0.7,
    power: 0.85,
    aggression: 0.3,
    spacing: 90,
    style: {
      scale: 1.1,
      girth: 1.45,
      headSize: 0.5,
      beardLength: 0,
      beardStyle: 'none',
      skin: '#4a4f5c',
      skinShade: '#2f3540',
      hair: '#20242d',
      hatColor: '#5b6270',
      tunicColor: '#39404c',
      jacketColor: '#2b313b',
      jacketAccent: '#37e6c8',
      spikes: 0,
      shades: false,
      outfit: 1,
      tattoo: 'none',
      cigar: false,
    },
    moves: { light: 'e_speaker_shove', heavy: 'e_bass_drop', ranged: 'e_sonic_blast' },
    weapon: 'gpu',
    points: 260,
    ai: {
      reactionFrames: 24,
      blockSkill: 0.1,
      comboSkill: 0.1,
      swarm: 0.4,
      behaviour: 'support',
    },
  },

  delivery_drone: {
    id: 'delivery_drone',
    name: 'Last-Mile Drone',
    health: 44,
    speed: 1.36,
    power: 0.8,
    aggression: 0.55,
    spacing: 70,
    style: {
      scale: 0.86,
      girth: 1.15,
      headSize: 0.5,
      beardLength: 0,
      beardStyle: 'none',
      skin: '#e9edf2',
      skinShade: '#aeb6c0',
      hair: '#3a4250',
      hatColor: '#ff8a3d',
      tunicColor: '#d8dee6',
      jacketColor: '#b7bfc9',
      jacketAccent: '#ff8a3d',
      spikes: 0,
      shades: false,
      outfit: 1,
      tattoo: 'barcode',
      cigar: false,
    },
    moves: { light: 'e_rotor_slash', ranged: 'e_package_drop' },
    weapon: 'chain',
    points: 200,
    ai: {
      reactionFrames: 10,
      blockSkill: 0,
      comboSkill: 0.15,
      swarm: 0.85,
      behaviour: 'erratic',
    },
  },

  // ── Humans without suits, which is somehow worse ───────────────────────────
  intern: {
    id: 'intern',
    name: 'Unpaid Intern',
    health: 34,
    speed: 1.18,
    power: 0.5,
    aggression: 0.95,
    spacing: 18,
    style: {
      scale: 1.16,
      girth: 0.8,
      headSize: 0.96,
      beardLength: 0.3,
      beardStyle: 'stubble',
      skin: '#efc09c',
      skinShade: '#bd8a63',
      hair: '#4a3626',
      hatColor: '#3a5f8a',
      tunicColor: '#5b7fa8',
      jacketColor: '#33445c',
      jacketAccent: '#8be0c8',
      spikes: 0,
      shades: false,
      outfit: 1,
      tattoo: 'none',
      cigar: false,
    },
    moves: { light: 'e_slap', heavy: 'e_laptop_swing', ranged: 'e_coffee_throw' },
    weapon: 'keyboard',
    points: 60,
    ai: {
      reactionFrames: 16,
      blockSkill: 0.03,
      comboSkill: 0.35,
      swarm: 1.0,
      behaviour: 'rusher',
    },
  },

  lobbyist: {
    id: 'lobbyist',
    name: 'Government Affairs',
    health: 96,
    speed: 0.94,
    power: 1.1,
    aggression: 0.45,
    spacing: 50,
    style: {
      scale: 1.24,
      girth: 1.16,
      headSize: 0.92,
      beardLength: 0,
      beardStyle: 'none',
      skin: '#e6b892',
      skinShade: '#b4855c',
      hair: '#7a6a58',
      hatColor: '#2a2436',
      tunicColor: '#4a3f5e',
      jacketColor: '#332b44',
      jacketAccent: '#d9b451',
      spikes: 0,
      shades: false,
      outfit: 1,
      tattoo: 'none',
      cigar: true,
    },
    moves: { light: 'e_briefcase', heavy: 'e_handshake', ranged: 'e_donation' },
    weapon: 'bat',
    points: 300,
    ai: {
      reactionFrames: 20,
      blockSkill: 0.4,
      comboSkill: 0.25,
      swarm: 0.3,
      behaviour: 'spacer',
    },
  },
};
